CREATE TABLE nc2.dim_date
(
  ID INT PRIMARY KEY NOT NULL
, DAY_DESC TINYTEXT
, DAY_DATE DATETIME
, YEAR_NUMBER INT
, MONTH_NUMBER INT
, DAY_OF_YEAR_NUMBER INT
, DAY_OF_MONTH_NUMBER INT
, DAY_OF_WEEK_NUMBER INT
, WEEK_OF_YEAR_NUMBER INT
, DAY_NAME VARCHAR(30)
, MONTH_NAME VARCHAR(30)
, QUARTER_NUMBER INT
, QUARTER_NAME VARCHAR(2)
, YEAR_QUARTER_NAME VARCHAR(32)
, WEEKEND_IND CHAR(1)
, DAYS_IN_MONTH_QTY INT
, WEEK_SK INT
, WEEK_NAME VARCHAR(32)
, WEEK_OF_MONTH_NUMBER INT
, WEEK_OF_MONTH_NAME TINYTEXT
, YEAR_SK INT
, MONTH_SK INT
, QUARTER_SK INT
, DAY_OF_WEEK_SORT_NAME VARCHAR(60)
, YEAR_SORT_NUMBER VARCHAR(4)
);